// ── 共用假題庫（待接 Firestore 後移除） ──────────────────────────
import { QuestionDoc } from '@/types'

export const MOCK_QUESTIONS: QuestionDoc[] = [
  {
    id: 'q-001',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶來電表示無法登入系統，已確認帳號密碼輸入正確，但仍顯示「帳號或密碼錯誤」。',
    content: '以下哪個處理步驟應優先執行？',
    options: {
      A: '請客戶重新設定密碼',
      B: '確認客戶帳號是否因多次錯誤而被系統鎖定',
      C: '告知客戶稍後再試，並掛斷電話',
      D: '直接轉接技術部門，不做任何確認',
    },
    answer: 'B',
    explanation: '帳號鎖定是登入失敗最常見的原因，應優先確認此狀態，再引導客戶解鎖或重設密碼。',
    enabled: true,
    sourceId: 'sheet-q-001',
    syncedAt: new Date(),
  },
  {
    id: 'q-002',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶情緒激動，在電話中大聲抱怨產品問題，並使用不雅語言。',
    content: '身為客服人員，最適當的處理方式是？',
    options: {
      A: '立即掛斷電話，避免承受言語攻擊',
      B: '以同樣強硬的態度回應，要求客戶冷靜',
      C: '保持冷靜，同理客戶情緒，說明公司規定後禮貌提醒溝通方式',
      D: '一言不發，等待客戶自行冷靜',
    },
    answer: 'C',
    explanation: '保持專業與同理心是處理激動客戶的關鍵。先認同情緒，再說明規定，最後禮貌提醒，能有效緩和情勢。',
    enabled: true,
    sourceId: 'sheet-q-002',
    syncedAt: new Date(),
  },
  {
    id: 'q-003',
    type: 'choice',
    difficulty: 'medium',
    context: '客戶詢問訂單出貨狀態，查詢後發現物流資訊顯示「已送達」，但客戶表示未收到。',
    content: '下列哪個處理流程最為完整？',
    options: {
      A: '告知客戶物流顯示已送達，要求客戶自行追蹤',
      B: '立即協助開立重送單，不需查明原因',
      C: '確認配送地址 → 聯繫物流公司查明 → 告知客戶後續處理方案與時程',
      D: '請客戶等 3 天後若仍未收到再聯絡',
    },
    answer: 'C',
    explanation: '完整的處理應包含：確認資料正確性、協調相關方查明原因、主動告知客戶進度，缺少任一環節都可能造成客戶不滿。',
    enabled: true,
    sourceId: 'sheet-q-003',
    syncedAt: new Date(),
  },
  {
    id: 'q-004',
    type: 'qa',
    difficulty: 'medium',
    context: '客戶因產品瑕疵申請退款，但超過退款期限 2 天。主管尚未上班，無法即時取得授權。',
    content: '請說明你在此情況下的處理方式，並說明理由。',
    answer: '應先向客戶表達理解與同理，說明退款政策規範，並承諾會向主管反映特殊情況，於時限內（建議當天）給予明確回覆。同時記錄案件細節，避免客戶重複說明。不可自行承諾超出職權的退款，但也不應讓客戶在無回應中等待。',
    explanation: '此題考核「同理心」、「流程遵循」與「承諾管理」三大能力，缺一不可。',
    enabled: true,
    sourceId: 'sheet-q-004',
    syncedAt: new Date(),
  },
  {
    id: 'q-005',
    type: 'choice',
    difficulty: 'medium',
    context: '客戶要求在電話中變更帳戶電子信箱，但系統規定須通過信箱驗證才能變更。',
    content: '客服人員應如何回應？',
    options: {
      A: '直接在系統後台幫客戶變更，不需驗證',
      B: '說明系統安全機制，引導客戶透過舊信箱自助驗證後進行變更',
      C: '要求客戶到實體門市辦理，電話無法處理',
      D: '請客戶提供身分證字號，確認身份後直接變更',
    },
    answer: 'B',
    explanation: '帳戶安全政策須遵守，但應以輔助引導而非拒絕的方式回應客戶，說明原因並提供可行的自助流程。',
    enabled: true,
    sourceId: 'sheet-q-005',
    syncedAt: new Date(),
  },
  {
    id: 'q-006',
    type: 'qa',
    difficulty: 'advanced',
    context: '客戶反映已連續三次向客服反映同一問題，但每次都須重新說明，感到非常沮喪。',
    content: '請分析此案例暴露了哪些客服流程問題，並提出改善建議。',
    answer: '問題包含：(1) 案件記錄不完整或未正確傳遞；(2) 跨客服人員的交接機制不足；(3) 問題解決率低，未有效追蹤至結案。改善建議：確實記錄每次對話重點並更新案件狀態，設定未結案件自動提醒，以及主動聯繫客戶確認問題是否解決，而非等待客戶再次來電。',
    explanation: '此題考核客服系統思維與流程改善能力，優秀答案應涵蓋問題診斷與具體可行的改善方案。',
    enabled: true,
    sourceId: 'sheet-q-006',
    syncedAt: new Date(),
  },
  {
    id: 'q-007',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶在結束通話前說：「你是我遇過最有耐心的客服！」',
    content: '最適當的回應方式是？',
    options: {
      A: '謙虛說「沒有啦，這是我應該做的」後立即掛斷',
      B: '真誠感謝客戶的肯定，再次確認問題已解決，並歡迎客戶日後聯繫',
      C: '順勢推銷其他產品或服務',
      D: '詢問客戶是否願意填寫滿意度調查',
    },
    answer: 'B',
    explanation: '正向收尾能強化客戶關係，應真誠接受讚美、確認服務完整，讓客戶帶著滿意的印象結束通話。',
    enabled: true,
    sourceId: 'sheet-q-007',
    syncedAt: new Date(),
  },
  {
    id: 'q-008',
    type: 'qa',
    difficulty: 'advanced',
    context: '同時有三位客戶在線上等待，每位等待超過 10 分鐘，你目前正在處理一個複雜退款案。',
    content: '請描述你會如何進行工作優先序管理，並說明你的決策依據。',
    answer: '應評估當前案件是否可暫停（如等待主管回覆），若可暫停，先以簡短說明對正在等待的客戶致歉並告知預計時間，再回到主要案件。判斷優先序的依據：緊急程度（如配送問題）、等待時間、案件複雜度。同時應通知主管或同事協助分流，避免一人包攬造成所有客戶滿意度下降。',
    explanation: '此題測試多工處理能力與客戶體驗意識，重點在於「溝通」與「資源調度」，而非單純的速度。',
    enabled: true,
    sourceId: 'sheet-q-008',
    syncedAt: new Date(),
  },
]

export const MOCK_QUESTIONS_MAP = Object.fromEntries(
  MOCK_QUESTIONS.map((q) => [q.id, q])
)
