// ── 共用假題庫（待接 Firestore 後移除） ──────────────────────────
import { QuestionDoc } from '@/types'

export const MOCK_QUESTIONS: QuestionDoc[] = [
  {
    id: 'q-001',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶來電表示無法登入系統，已確認帳號密碼輸入正確，但仍顯示「帳號或密碼錯誤」。',
    content: '以下哪個處理步驟應優先執行？',
    options: {
      A: '請客戶重新設定密碼',
      B: '確認客戶帳號是否因多次錯誤而被系統鎖定',
      C: '告知客戶稍後再試，並掛斷電話',
      D: '直接轉接技術部門，不做任何確認',
    },
    answer: 'B',
    explanation: '帳號鎖定是登入失敗最常見的原因，應優先確認此狀態，再引導客戶解鎖或重設密碼。',
    enabled: true,
    sourceId: 'sheet-q-001',
    syncedAt: new Date(),
  },
  {
    id: 'q-002',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶情緒激動，在電話中大聲抱怨產品問題，並使用不雅語言。',
    content: '身為客服人員，最適當的處理方式是？',
    options: {
      A: '立即掛斷電話，避免承受言語攻擊',
      B: '以同樣強硬的態度回應，要求客戶冷靜',
      C: '保持冷靜，同理客戶情緒，說明公司規定後禮貌提醒溝通方式',
      D: '一言不發，等待客戶自行冷靜',
    },
    answer: 'C',
    explanation: '保持專業與同理心是處理激動客戶的關鍵。先認同情緒，再說明規定，最後禮貌提醒，能有效緩和情勢。',
    enabled: true,
    sourceId: 'sheet-q-002',
    syncedAt: new Date(),
  },
  {
    id: 'q-003',
    type: 'choice',
    difficulty: 'medium',
    context: '客戶詢問訂單出貨狀態，查詢後發現物流資訊顯示「已送達」，但客戶表示未收到。',
    content: '下列哪個處理流程最為完整？',
    options: {
      A: '告知客戶物流顯示已送達，要求客戶自行追蹤',
      B: '立即協助開立重送單，不需查明原因',
      C: '確認配送地址 → 聯繫物流公司查明 → 告知客戶後續處理方案與時程',
      D: '請客戶等 3 天後若仍未收到再聯絡',
    },
    answer: 'C',
    explanation: '完整的處理應包含：確認資料正確性、協調相關方查明原因、主動告知客戶進度，缺少任一環節都可能造成客戶不滿。',
    enabled: true,
    sourceId: 'sheet-q-003',
    syncedAt: new Date(),
  },
  {
    id: 'q-004',
    type: 'qa',
    difficulty: 'medium',
    context: '客戶因產品瑕疵申請退款，但超過退款期限 2 天。主管尚未上班，無法即時取得授權。',
    content: '請說明你在此情況下的處理方式，並說明理由。',
    answer: '應先向客戶表達理解與同理，說明退款政策規範，並承諾會向主管反映特殊情況，於時限內（建議當天）給予明確回覆。同時記錄案件細節，避免客戶重複說明。不可自行承諾超出職權的退款，但也不應讓客戶在無回應中等待。',
    explanation: '此題考核「同理心」、「流程遵循」與「承諾管理」三大能力，缺一不可。',
    enabled: true,
    sourceId: 'sheet-q-004',
    syncedAt: new Date(),
  },
  {
    id: 'q-005',
    type: 'choice',
    difficulty: 'medium',
    context: '客戶要求在電話中變更帳戶電子信箱，但系統規定須通過信箱驗證才能變更。',
    content: '客服人員應如何回應？',
    options: {
      A: '直接在系統後台幫客戶變更，不需驗證',
      B: '說明系統安全機制，引導客戶透過舊信箱自助驗證後進行變更',
      C: '要求客戶到實體門市辦理，電話無法處理',
      D: '請客戶提供身分證字號，確認身份後直接變更',
    },
    answer: 'B',
    explanation: '帳戶安全政策須遵守，但應以輔助引導而非拒絕的方式回應客戶，說明原因並提供可行的自助流程。',
    enabled: true,
    sourceId: 'sheet-q-005',
    syncedAt: new Date(),
  },
  {
    id: 'q-006',
    type: 'qa',
    difficulty: 'advanced',
    context: '客戶反映已連續三次向客服反映同一問題，但每次都須重新說明，感到非常沮喪。',
    content: '請分析此案例暴露了哪些客服流程問題，並提出改善建議。',
    answer: '問題包含：(1) 案件記錄不完整或未正確傳遞；(2) 跨客服人員的交接機制不足；(3) 問題解決率低，未有效追蹤至結案。改善建議：確實記錄每次對話重點並更新案件狀態，設定未結案件自動提醒，以及主動聯繫客戶確認問題是否解決，而非等待客戶再次來電。',
    explanation: '此題考核客服系統思維與流程改善能力，優秀答案應涵蓋問題診斷與具體可行的改善方案。',
    enabled: true,
    sourceId: 'sheet-q-006',
    syncedAt: new Date(),
  },
  {
    id: 'q-007',
    type: 'choice',
    difficulty: 'basic',
    context: '客戶在結束通話前說：「你是我遇過最有耐心的客服！」',
    content: '最適當的回應方式是？',
    options: {
      A: '謙虛說「沒有啦，這是我應該做的」後立即掛斷',
      B: '真誠感謝客戶的肯定，再次確認問題已解決，並歡迎客戶日後聯繫',
      C: '順勢推銷其他產品或服務',
      D: '詢問客戶是否願意填寫滿意度調查',
    },
    answer: 'B',
    explanation: '正向收尾能強化客戶關係，應真誠接受讚美、確認服務完整，讓客戶帶著滿意的印象結束通話。',
    enabled: true,
    sourceId: 'sheet-q-007',
    syncedAt: new Date(),
  },
  {
    id: 'q-008',
    type: 'qa',
    difficulty: 'advanced',
    context: '同時有三位客戶在線上等待，每位等待超過 10 分鐘，你目前正在處理一個複雜退款案。',
    content: '請描述你會如何進行工作優先序管理，並說明你的決策依據。',
    answer: '應評估當前案件是否可暫停（如等待主管回覆），若可暫停，先以簡短說明對正在等待的客戶致歉並告知預計時間，再回到主要案件。判斷優先序的依據：緊急程度（如配送問題）、等待時間、案件複雜度。同時應通知主管或同事協助分流，避免一人包攬造成所有客戶滿意度下降。',
    explanation: '此題測試多工處理能力與客戶體驗意識，重點在於「溝通」與「資源調度」，而非單純的速度。',
    enabled: true,
    sourceId: 'sheet-q-008',
    syncedAt: new Date(),
  },
]

export const MOCK_QUESTIONS_MAP = Object.fromEntries(
  MOCK_QUESTIONS.map((q) => [q.id, q])
)

// ── 申論模式假題庫（待接 Firestore 後移除） ────────────────────────
export const MOCK_ESSAY_QUESTIONS: QuestionDoc[] = [
  {
    id: 'eq-001',
    type: 'essay',
    difficulty: 'basic',
    context: '你剛接手一位等待超過 20 分鐘的客戶，客戶情緒明顯不耐煩，且不斷重複「你們公司根本沒有效率」。',
    content: '請描述你如何開場，並在前 2 分鐘內穩定客戶情緒，同時取得客戶信任以順利進行後續服務。',
    enabled: true,
    sourceId: 'sheet-eq-001',
    syncedAt: new Date(),
  },
  {
    id: 'eq-002',
    type: 'essay',
    difficulty: 'basic',
    context: '客戶來電詢問訂單出貨狀態，系統顯示「配送中」，但客戶表示已超過預計送達日期 3 天仍未收到。',
    content: '請說明你的完整處理流程，包含資訊確認、內部協調與對客戶的回覆方式，並說明每個步驟的目的。',
    enabled: true,
    sourceId: 'sheet-eq-002',
    syncedAt: new Date(),
  },
  {
    id: 'eq-003',
    type: 'essay',
    difficulty: 'medium',
    context: '客戶購買的電子產品在使用一個月後發生故障，要求全額退款，但公司政策規定超過 30 天只提供維修服務。客戶表示產品根本是瑕疵品，拒絕接受維修，態度強硬。',
    content: '你將如何在遵守公司政策的前提下，處理這位客戶的投訴？請詳細說明你的溝通策略、可以提供的替代方案，以及如何引導客戶接受解決方案。',
    enabled: true,
    sourceId: 'sheet-eq-003',
    syncedAt: new Date(),
  },
  {
    id: 'eq-004',
    type: 'essay',
    difficulty: 'medium',
    context: '你在一天之內連續接到 5 位客戶投訴同一個系統功能出現錯誤，但技術部門尚未確認問題，也無法提供預計修復時間。',
    content: '在技術問題尚未解決的情況下，你如何對每一位客戶進行妥善回覆？請說明你會傳達哪些訊息、如何設定客戶預期，以及後續的跟進機制。',
    enabled: true,
    sourceId: 'sheet-eq-004',
    syncedAt: new Date(),
  },
  {
    id: 'eq-005',
    type: 'essay',
    difficulty: 'medium',
    context: '你服務的客戶是一位老年人，對於操作手機 APP 不熟悉，在電話中多次詢問相同操作步驟，且常常誤解你的說明，通話已進行超過 30 分鐘，後方仍有多位客戶等候。',
    content: '請說明你在此情況下如何平衡服務品質與通話效率，並描述你會採用哪些溝通技巧幫助客戶理解操作步驟，同時不讓客戶感到被催促或不受重視。',
    enabled: true,
    sourceId: 'sheet-eq-005',
    syncedAt: new Date(),
  },
  {
    id: 'eq-006',
    type: 'essay',
    difficulty: 'advanced',
    context: '客戶反映三個月前反映的問題至今未解決，中間曾接觸過 4 位不同的客服人員，每次都需要重新說明問題。客戶明確表示「下次我直接找媒體投訴」。',
    content: '請分析此案例暴露的客服流程問題，並提出具體的改善建議。同時說明你在當下通話中會如何處理，以及如何確保這個案件能在你手中徹底結案。',
    enabled: true,
    sourceId: 'sheet-eq-006',
    syncedAt: new Date(),
  },
  {
    id: 'eq-007',
    type: 'essay',
    difficulty: 'advanced',
    context: '公司即將推出新的收費政策，部分舊客戶原本享有的優惠方案將被取消，你負責致電通知這批客戶，預期會有大量不滿情緒。',
    content: '請設計你在這波外撥通知中的標準話術框架，說明你如何開場、傳達壞消息、處理客戶不滿，以及如何在通話結束時維持客戶對品牌的正面觀感。',
    enabled: true,
    sourceId: 'sheet-eq-007',
    syncedAt: new Date(),
  },
  {
    id: 'eq-008',
    type: 'essay',
    difficulty: 'advanced',
    context: '你注意到同事在處理客戶投訴時，習慣使用「公司規定就是這樣」作為拒絕理由，且態度偏冷漠，已有 2 位客戶針對該同事留下負評。',
    content: '作為同事而非主管，你如何處理這個情況？請說明你的觀察方式、溝通策略，以及你認為良好客服應具備的核心態度，並對比分析你同事的行為問題所在。',
    enabled: true,
    sourceId: 'sheet-eq-008',
    syncedAt: new Date(),
  },
  {
    id: 'eq-009',
    type: 'essay',
    difficulty: 'medium',
    context: '在高峰時段，你同時處理著一個正在線上等候的客戶，以及一個剛被轉接過來的緊急投訴案件（客戶揚言要立即取消合約）。',
    content: '請說明你的優先序判斷邏輯，以及你如何在不讓任何一方感到被忽視的情況下，同時處理這兩件事。請具體描述你會對兩位客戶分別說什麼。',
    enabled: true,
    sourceId: 'sheet-eq-009',
    syncedAt: new Date(),
  },
  {
    id: 'eq-010',
    type: 'essay',
    difficulty: 'basic',
    context: '這是你入職客服部門的第一個月。你被要求在月底前提交一份「自我服務品質評估報告」，回顧本月的服務表現。',
    content: '請撰寫這份評估報告的核心內容，包含：你認為自己做得最好的 2 項能力、最需要改善的 1 項能力，以及下個月的具體改善計畫。請以真實且有深度的方式回答，避免流於表面。',
    enabled: true,
    sourceId: 'sheet-eq-010',
    syncedAt: new Date(),
  },
]

export const MOCK_ESSAY_QUESTIONS_MAP = Object.fromEntries(
  MOCK_ESSAY_QUESTIONS.map((q) => [q.id, q])
)
